export const mernPlaylist = [
  {
    id: 1,
    image: 'mern1.webp',
    date: 'Feb 20, 2021',
    latest: false,
    trending: true,
    author: 'CodeDexterous',
    timeline: '13:05',
    title: 'Create a simple drag and drop web-page builder in React',
    badge: 'Grapes JS MERN',
    videoUrl: 'j9THxdwbxEE',
    description: `We have integrated Grapes JS with HTML 5. In this video, we will integrate Grapes JS with React to create our Web Page Builder.
    Website  Builder, No Code, Zero Code.
    Create Editor to be used to create a website just by dragging & dropping.
    Drag & drop Website creator.`,
  },
  {
    id: 2,
    image: 'mern1.webp',
    date: 'May 27, 2021',
    trending: false,
    latest: false,
    author: 'CodeDexterous',
    timeline: '04:45',
    title: 'Recap and add Router to our application - React Hooks',
    badge: 'Grapes JS MERN',
    videoUrl: 'OBnwNqPuGjk',
    description: `I got many requests to add more videos to this series, so here I am. This is the first time I am trying to add generated voice in videos to make it more clear. I am not sure how it is so please give me your feedback.
    Since I am adding video in this series after a long time so I just give some basic overview and how it going to be.
    I am very thankful to all of the viewers for such great responses. I would love to get more feedback/suggestions from you. Please like, share, and subscribe.`,
  },
  {
    id: 3,
    image: 'mern1.webp',
    date: 'June 20, 2021',
    trending: false,
    latest: false,
    author: 'CodeDexterous',
    timeline: '07:57',
    title: 'Create UI to show list of pages and Form to Create New Page',
    badge: 'Grapes JS MERN',
    videoUrl: '6iO7l6KI85U',
    description: `I got many requests to add more videos to this series, so here I am. Today I will design the pages routes in our application. I am very thankful to all of the viewers for such great responses. I would love to get more feedback/suggestions from you. Please like, share, and subscribe.`,
  },
  {
    id: 4,
    date: 'Jul 4, 2021',
    image: 'mern1.webp',
    latest: false,
    trending: false,
    author: 'CodeDexterous',
    timeline: '11:49',
    title: 'Show all pages and Create new Page',
    badge: 'Grapes JS MERN',
    videoUrl: 'nKmzZb8Ev1I',
    description: `In this video, we will load pages from Database and then create a new page. I am very thankful to all of the viewers for such great responses. I would love to get more feedback/suggestions from you. Please like, share, and subscribe.`,
  },
  {
    id: 5,
    date: 'Jul 11, 2021',
    image: 'mern1.webp',
    latest: false,
    author: 'CodeDexterous',
    trending: false,
    timeline: '09:26',
    title: 'Customise Editor UI and Save Page Content to Database',
    badge: 'Grapes JS MERN',
    videoUrl: 'p5IRWREqxr0',
    description: `In this video, we will customise Grapes js Editor as we did for our HTML project. We also going to load and save content from Editor to Pages specific in Mongo Database.
    Video to follow to create Node API and Understand the customisation of Grapes js.`,
  },
  {
    id: 6,
    date: 'Jul 23, 2021',
    image: 'mern2.jpg',
    latest: false,
    trending: true,
    author: 'CodeDexterous',
    timeline: '10:45',
    title: 'Asset Manager in Grapes JS - Web Page Editor - React Editor',
    badge: 'Grapes JS MERN',
    description: `So for now, we saw how to use Grapes JS with Vaniall JS/HTML and also with React. In this, I will try to answer a few questions. And also I am explaining the easiest way to use Asset Manager. After watching this video you will be able to use your images in Grapes JS Editor.`,
    videoUrl: '3Lj2mXFN5ts',
  },
  {
    id: 7,
    date: 'Jul 31, 2021',
    image: 'mern2.jpg',
    latest: false,
    author: 'CodeDexterous',
    trending: false,
    timeline: '05:19',
    title: 'Add more Configuration in Style Manager and Buttons to Panel',
    badge: 'Grapes JS MERN',
    videoUrl: 'E_M30yscbQU',
    description: `So for now, we saw how to use Grapes JS with Vaniall JS/HTML and also with React. In this, I will try to answer a few questions. Today I added more settings in the style manager to add Styling to our Page Content. I also added buttons to the panel to Save Content on click, Clear Canvas, Redo, and Undo by using Custom Commands.`,
  },
  {
    id: 8,
    image: 'mern2.jpg',
    date: 'Aug 15, 2021',
    trending: false,
    latest: false,
    author: 'CodeDexterous',
    timeline: '14:47',
    title: 'Tailwind CSS',
    badge: 'Grapes JS MERN',
    videoUrl: 'MtiJ_9qWfQc',
    description: `In this video, I try to integrate Tailwind CSS with Grapes JS in React JS.`,
  },
  {
    id: 9,
    date: 'Aug 21, 2021',
    image: 'mern2.jpg',
    latest: false,
    trending: false,
    author: 'CodeDexterous',
    timeline: '17:39',
    title: 'Create Custom Swiper Plugin for Grapes JS',
    badge: 'Grapes JS MERN',
    videoUrl: 'qZ-POurckTs',
    description: `In this video, we will create a Grapes JS plugin for Swiper and use it. It will include creating Custom Blocks, Components.`,
  },
  {
    id: 10,
    date: 'Sep 3, 2021',
    trending: true,
    image: 'mern2.jpg',
    latest: false,
    author: 'CodeDexterous',
    timeline: '02:45',
    title: 'Auto Close all categories of Blocks ',
    badge: 'Grapes JS MERN',
    videoUrl: 'R45czM-UISQ',
    description: `A user has asked on Github how to auto-close all categories of blocks when they first loaded. Sometimes it is very important, because if you have many categories then it is difficult to scroll to the bottom to see all categories.
    So in today's video, we will auto close the Block's Categories when it is loaded.`,
  },
  {
    id: 11,
    image: 'mern5.jpg',
    date: 'Sep 4, 2021',
    latest: false,
    trending: false,
    author: 'CodeDexterous',
    timeline: '03:40',
    title: 'Bootstrap Plugin in Grapes JS',
    badge: 'Grapes JS MERN',
    videoUrl: 'HI0VVgcxdpM',
    description: `Many users are facing issues with Forms. So today we are going to add a Bootstrap plugin.
    `,
  },
  {
    id: 12,
    date: 'Sep 18, 2021',
    image: 'mern2.jpg',
    author: 'CodeDexterous',
    latest: false,
    timeline: '06:52',
    trending: false,
    title: 'Export HTML/CSS/JS',
    badge: 'Grapes JS MERN',
    videoUrl: '8KEaZ1VhGYo',
    description: `Hi Guys, today's video is a very hot topic video. A lot of users are facing this issue and asking to create a video on this. So, finally, in today's video, we will see how can we export the designed template from Grapes JS. 
    So let get started.`,
  },
  {
    id: 13,
    image: 'mern3.webp',
    date: 'Sep 30, 2021',
    trending: false,
    latest: false,
    author: 'CodeDexterous',
    timeline: '02:50',
    title: 'How to use CDN CSS and JS in Grapes JS',
    badge: 'Grapes JS MERN',
    videoUrl: 'x3WS5VA55qA',
    description: `Hi Guys, today's video is a very hot topic video. A lot of users are facing this issue and asking to create a video on this. So, finally, in today's video, we will see how can we use CDN style and JS in Grapes JS Plugin.`,
  },
  {
    id: 14,
    trending: false,
    latest: false,
    date: 'Oct 2, 2021',
    image: 'mern2.jpg',
    author: 'CodeDexterous',
    timeline: '08:41',
    title: 'Gradient Setting in Style Manager',
    badge: 'Grapes JS MERN',
    videoUrl: '_MMw5_B7v1A',
    description: `Hi Guys, Today's video is about adding more features to Style Manager. Today we will use the Gradient Plugin.`,
  },
  {
    id: 15,
    latest: false,
    trending: false,
    date: 'Oct 5, 2021',
    image: 'mern2.jpg',
    author: 'CodeDexterous',
    timeline: '09:13',
    title: 'Preview in Grapes JS',
    badge: 'Grapes JS MERN',
    videoUrl: 'J_ucw-xCsRE',
    description: `Hi Guys,
    In today's video, we will a new feature of Grapes JS, which was present from starting of this series. But, because of our customisation, it was missed.`,
  },
  {
    id: 16,
    latest: false,
    trending: false,
    image: 'mern2.jpg',
    date: 'Oct 15, 2021',
    author: 'CodeDexterous',
    timeline: '01:19',
    title: 'Remove class - Style Manager',
    badge: 'Grapes JS MERN',
    videoUrl: 'sJNxbff8Msc',
    description: ``,
  },
  {
    id: 17,
    latest: false,
    image: 'mern2.jpg',
    trending: false,
    date: 'Oct 23, 2021',
    author: 'CodeDexterous',
    timeline: '13:42',
    title: 'Refactor and Page List in Editor',
    badge: 'Grapes JS MERN',
    videoUrl: 'IoDgCqeEgbY',
    description: `Hi Guys,
    Today, we will refactor code and separate them into multiple functions and files. We will also add a pages list into the sidebar.
    Later, we will also add functionality to add pages directly from here, instead of Home.`,
  },
  {
    id: 18,
    latest: true,
    trending: false,
    image: 'mern2.jpg',
    date: 'Oct 27, 2021',
    author: 'CodeDexterous',
    timeline: '18:09',
    title: 'Add Redux for better scalability ',
    badge: 'Grapes JS MERN',
    videoUrl: 'ahWc_rxQ1Jc',
    description: `Hi Guys,
    Now, we should maintain a global store for our application. So we can access it from anywhere and add more functionality to it. For the same, today we will integrate Redux into our application`,
  },
  {
    id: 19,
    latest: true,
    trending: false,
    image: 'mern2.jpg',
    date: 'Nov 7, 2021',
    author: 'CodeDexterous',
    timeline: '13:02',
    title: 'Create Page from Editor Page',
    badge: 'Grapes JS MERN',
    videoUrl: '92kyf0-JrgA',
    description: `Hi Guys,
    Today, we will create a page from Editor Page itself. We will use redux`,
  },
  {
    id: 20,
    image: 'mern2.jpg',
    trending: false,
    latest: true,
    date: 'Jan 25, 2022',
    author: 'CodeDexterous',
    timeline: '03:43',
    title: 'Render HTML from Database',
    badge: 'Grapes JS MERN',
    videoUrl: 'apWVy-uTMU4',
    description: `Hi Guys,
    A lot of users are facing issues with rendering the HTML from the Database which they have created using Grapes JS Editor. So today we will see how to do that. `,
  },
  {
    id: 21,
    latest: true,
    trending: false,
    date: 'Feb 7, 2022',
    image: 'mern2.jpg',
    author: 'CodeDexterous',
    timeline: '09:54',
    title: 'Hide Sidebar when component is selected',
    badge: 'Grapes JS MERN',
    videoUrl: 'Pdr9Yqep6SI',
    description: `Hi Guys,
    Today, we will hide the sidebar once a component is selected inside the Canvas.  `,
  },
  {
    id: 22,
    trending: false,
    date: 'Feb 13, 2022',
    latest: true,
    image: 'mern2.jpg',
    author: 'CodeDexterous',
    timeline: '09:26',
    title: "Add option in Component's Toolbar",
    badge: 'Grapes JS MERN',
    videoUrl: 'PJ-ywvQ4U0U',
    description: `Hi Guys,
    As asked by a user, today we will add an option in the component's toolbar.`,
  },
]
